In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
type(x_data)

torch.Tensor

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.0544, 0.8095],
        [0.3544, 0.1749]]) 



In [7]:
# Attributes of tensor

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
# Moving tensor to GPU
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [9]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


## Tensor Operations

In [10]:
a = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
b = torch.eye(3)

In [12]:
b

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [14]:
a + b

tensor([[ 2.,  2.,  3.],
        [ 4.,  6.,  6.],
        [ 7.,  8., 10.]])

In [15]:
a * b

tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])

In [16]:
a/b

tensor([[1., inf, inf],
        [inf, 5., inf],
        [inf, inf, 9.]])

In [17]:
a @ b

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [18]:
# Slicing
a[:]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [19]:
a[:1]

tensor([[1., 2., 3.]])

In [20]:
a[1:]

tensor([[4., 5., 6.],
        [7., 8., 9.]])

In [21]:
a[:,1:]

tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])

In [22]:
a[:,:1]

tensor([[1.],
        [4.],
        [7.]])

In [24]:
# Concatenation
torch.cat((a,b))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [25]:
# Concatenation
torch.cat((a,b), axis = 1)

tensor([[1., 2., 3., 1., 0., 0.],
        [4., 5., 6., 0., 1., 0.],
        [7., 8., 9., 0., 0., 1.]])

## Matrix Multiplication

In [27]:
import time

In [26]:
def mmNestedLoop(x, y, size):
  # O(n^2)
  res = torch.zeros((size, size))
  for i in range(size):
    for j in range(size):
      row = x[i, :]
      col = y[:,j]
      res[i,j] = torch.sum(row * col)
  return res

In [28]:
def mmVectorized(x, y):
  return torch.mm(x, y)

In [29]:
def mmVectorizedGPU(x,y):
  return torch.mm(x.to('cuda'), y.to('cuda'))

In [30]:
x = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])
y = torch.Tensor([[10,20,30], [40,50,60], [70,80,90]])

In [37]:
start = time.time()
print(mmNestedLoop(x, y, 3))
end = time.time()
print("Time taken for nested loop : ", end - start)

tensor([[ 300.,  360.,  420.],
        [ 660.,  810.,  960.],
        [1020., 1260., 1500.]])
Time taken for nested loop :  0.0012907981872558594


In [38]:
start = time.time()
print(mmVectorized(x, y))
end = time.time()
print("Time taken for Vectorized : ", end - start)

tensor([[ 300.,  360.,  420.],
        [ 660.,  810.,  960.],
        [1020., 1260., 1500.]])
Time taken for Vectorized :  0.002481698989868164


In [39]:
start = time.time()
print(mmVectorizedGPU(x, y))
end = time.time()
print("Time taken for Vectorized with GPU : ", end - start)

tensor([[ 300.,  360.,  420.],
        [ 660.,  810.,  960.],
        [1020., 1260., 1500.]], device='cuda:0')
Time taken for Vectorized with GPU :  0.0028078556060791016
